name: Docker Image CI
on:
  push:
    branches:
    - feat/push-dockerhub
    - v*-v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Retrieve Github branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '[|/]' '-')"
      id: branch_name
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag germainlefebvre4/helm-kubectl-docker:${{ steps.branch_name.outputs.branch }}
    - name: Test run container - Print Helm version
      run: docker run --rm germainlefebvre4/helm-kubectl-docker:${{ steps.branch_name.outputs.branch }} version --client
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: germainlefebvre4/helm-kubectl-docker:${{ steps.branch_name.outputs.branch }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

