name: Docker Image CI
on:
  push:
    branches:
    - v*-v*
    - chore/github-matrix
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl_version:
          - v1.16.4
          - v1.16.3
          - v1.16.2
          - v1.16.1
          - v1.16.0
          - v1.15.7
          - v1.15.6
          - v1.15.5
          - v1.15.4
          - v1.15.3
          - v1.15.2
          - v1.15.1
          - v1.15.0
          - v1.14.10
          - v1.14.9
          - v1.14.8
          - v1.14.7
          - v1.14.6
          - v1.14.5
          - v1.14.4
          - v1.14.3
          - v1.14.2
          - v1.14.1
          - v1.14.0
        helm_version:
          - v3.0.2
          - v3.0.1
          - v3.0.0
          - v2.16.1
          - v2.16.0
          - v2.15.2
          - v2.15.1
          - v2.15.0
          - v2.14.3
          - v2.14.2
          - v2.14.1
          - v2.14.0
          - v2.13.1
          - v2.13.0
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg KUBE_VERSION=${{ matrix.kubectl_version }} --build-arg HELM_VERSION=${{ matrix.helm_version }} --tag germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }}
    - name: Test run container - Print Kubectl version
      run: docker run --rm --entrypoint=kubectl germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }} version --client
    - name: Test run container - Print Helm version
      run: docker run --rm germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }} version --client
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
