name: Docker Image CI
on:
  push:
    branches:
    - feat/github-actions
    - v*-v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Retrieve Github branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag germainlefebvre4/helm-kubectl-docker:${{ steps.branch_name.outputs }}
    - name: Test run container - Print Helm version
      run: docker run -ti --rm germainlefebvre4/helm-kubectl-docker:${{ steps.branch_name.outputs.branch }} version --client
