name: Docker Image CI
on:
  push:
    branches:
    - master
    - autobuild
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl_version:
          - v1.17.4
          - v1.17.3
          - v1.17.2
          - v1.17.1
          - v1.17.0
          - v1.16.8
          - v1.16.7
          - v1.16.6
          - v1.16.5
          - v1.16.4
          - v1.16.3
          - v1.16.2
          - v1.16.1
          - v1.16.0
          - v1.15.11
          - v1.15.10
          - v1.15.9
          - v1.15.8
          - v1.15.7
          - v1.15.6
          - v1.15.5
          - v1.15.4
          - v1.15.3
          - v1.15.2
          - v1.15.1
          - v1.15.0
          - v1.14.10
          - v1.14.9
          - v1.14.8
          - v1.14.7
          - v1.14.6
          - v1.14.5
          - v1.14.4
          - v1.14.3
          - v1.14.2
          - v1.14.1
          - v1.14.0
        helm_version:
          #- v3.1.2
          #- v3.1.1
          #- v3.1.0
          #- v3.0.2
          #- v3.0.1
          #- v3.0.0
          - v2.16.4
          - v2.16.3
          - v2.16.2
          - v2.16.1
          - v2.16.0
          #- v2.15.2
          #- v2.15.1
          #- v2.15.0
    steps:
    - uses: actions/checkout@v1
    - name: Check if dockerhub version already exists
      run: echo "##[set-output name=rc;]$(curl -s -o /dev/null --write-out '%{http_code}' https://registry.hub.docker.com/v1/repositories/germainlefebvre4/helm-kubectl-docker/tags/${{ matrix.kubectl_version }}-${{ matrix.helm_version }} )"
      id: dockerhub
    - name: Check if kubectl version already exists
      run: echo "##[set-output name=rc;]$(curl -s --write-out '%{http_code}' -o /dev/null https://storage.googleapis.com/kubernetes-release/release/${{ matrix.kubectl_version }}/bin/linux/amd64/kubectl)"
      id: kubectl
    - name: Check if helm version already exists
      run: echo "##[set-output name=rc;]$(curl -s --write-out '%{http_code}' -o /dev/null https://get.helm.sh/helm-${{ matrix.helm_version }}-linux-amd64.tar.gz)"
      id: helm
    - name: Sumup return codes
      run: |
        echo "dockerhub: ${{ steps.dockerhub.outputs.rc }} (needs 404)"
        echo "kubectl: ${{ steps.kubectl.outputs.rc }} (needs 200)"
        echo "helm: ${{ steps.helm.outputs.rc }} (needs 200)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg KUBECTL_VERSION=${{ matrix.kubectl_version }} --build-arg HELM_VERSION=${{ matrix.helm_version }} --tag germainlefebvre4/helm-kubectl-docker:${{ matrix.kubectl_version }}-${{ matrix.helm_version }}
      if: steps.dockerhub.outputs.rc != 200 && steps.kubectl.outputs.rc == 200 && steps.helm.outputs.rc == 200
    - name: Test run container - Print Sh version
      run: docker run --rm germainlefebvre4/helm-kubectl-docker:${{ matrix.kubectl_version }}-${{ matrix.helm_version }} sh --help
      if: steps.dockerhub.outputs.rc != 200 && steps.kubectl.outputs.rc == 200 && steps.helm.outputs.rc == 200
    - name: Test run container - Print Kubectl version
      run: docker run --rm germainlefebvre4/helm-kubectl-docker:${{ matrix.kubectl_version }}-${{ matrix.helm_version }} kubectl version --client
      if: steps.dockerhub.outputs.rc != 200 && steps.kubectl.outputs.rc == 200 && steps.helm.outputs.rc == 200
    - name: Test run container - Print Helm version
      run: docker run --rm germainlefebvre4/helm-kubectl-docker:${{ matrix.kubectl_version }}-${{ matrix.helm_version }} helm version --client
      if: steps.dockerhub.outputs.rc != 200 && steps.kubectl.outputs.rc == 200 && steps.helm.outputs.rc == 200
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        KUBECTL_VERSION: ${{ matrix.kubectl_version }}
        HELM_VERSION: ${{ matrix.helm_version }}
      with:
        name: germainlefebvre4/helm-kubectl-docker:${{ matrix.kubectl_version }}-${{ matrix.helm_version }}
        buildargs: KUBECTL_VERSION,HELM_VERSION
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      if: steps.dockerhub.outputs.rc != 200 && steps.kubectl.outputs.rc == 200 && steps.helm.outputs.rc == 200

