name: Docker Image CI
on:
  push:
    branches:
    - v*-v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Retrieve Github branch name
      run: echo ${GITHUB_REF##*/}
      id: branch_name
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag germainlefebvre4/helm-kubectl-docker:${{ steps.branch_name.outputs }}
    - name: Test run container - Print Helm version
      run: docker run -ti --rm germainlefebvre4/helm-kubectl-docker:${{ steps.branch_name.outputs }} version --client
