name: Docker Image CI
on:
  push:
    branches:
    - v*-v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl_version:
          - 1.16.4
          - 1.15.7
          - 1.14.10
        helm_version:
          - 2.15.0
          - 2.16.0
          - 2.17.0
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }}
    - name: Test run container - Print Kubectl version
      run: docker run --rm --entrypoint=kubectl germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }} version --client
    - name: Test run container - Print Helm version
      run: docker run --rm germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }} version --client
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: germainlefebvre4/helm-kubectl-docker:dev-${{ matrix.kubectl_version }}-${{ matrix.helm_version }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
